/**
 * Generate brand files into overlay/ from overlay/apps/desktop/branding/
 * (brand.json and the logo mark logo.svg). Run after changing either:
 *
 *   pnpm brand
 *
 * Writes the application icons, the welcome wordmark, the Web favicon and
 * manifest, and the brand.ts data modules that patches/0006 reads. The upstream
 * versions of those brand.ts files hold the official copy, so a build without
 * this overlay keeps upstream's branding.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import sharp from 'sharp'
import { OVERLAY, ROOT, fail } from './lib.mjs'

const BRANDING = join(OVERLAY, 'apps', 'desktop', 'branding')
const brand = JSON.parse(readFileSync(join(BRANDING, 'brand.json'), 'utf8'))
for (const field of ['productName', 'accountProvider', 'accountName', 'welcomeDescription']) {
  if (brand[field] === undefined) fail(`brand.json misses ${field}`)
}
const logo = readFileSync(join(BRANDING, 'logo.svg'), 'utf8')
const viewBox = /viewBox="([\d.\s-]+)"/u.exec(logo)?.[1]?.split(/\s+/u).map(Number)
if (viewBox?.length !== 4) fail('logo.svg needs a viewBox')
const [, , logoWidth, logoHeight] = viewBox

function escapeXml(text) {
  return text.replace(/&/gu, '&amp;').replace(/</gu, '&lt;').replace(/>/gu, '&gt;').replace(/"/gu, '&quot;')
}

/** The logo mark placed in a box of the given height, horizontally centered on cx. */
function mark(cx, y, height) {
  const width = height * logoWidth / logoHeight
  const inner = logo.replace(/^[\s\S]*?<svg[^>]*>/u, '').replace(/<\/svg>\s*$/u, '')
  return `<svg x="${(cx - width / 2).toFixed(2)}" y="${y.toFixed(2)}" width="${width.toFixed(2)}" height="${height.toFixed(2)}" viewBox="${viewBox.join(' ')}">${inner}</svg>`
}

/** Mark width as a share of the icon plate width (brand.json iconMarkWidth). */
const ICON_MARK_WIDTH = brand.iconMarkWidth ?? 0.68

/** An app icon: a light rounded plate with the mark, following the upstream icon geometry. */
function icon(canvas, plate, radius, shadow) {
  const offset = (canvas - plate) / 2
  const markHeight = plate * ICON_MARK_WIDTH * logoHeight / logoWidth
  return `<svg width="${canvas}" height="${canvas}" viewBox="0 0 ${canvas} ${canvas}" fill="none" xmlns="http://www.w3.org/2000/svg">
<defs>
  <linearGradient id="plate" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#FFFFFF"/><stop offset="1" stop-color="#EEF3F9"/></linearGradient>
  <filter id="shadow" x="-20%" y="-20%" width="140%" height="140%"><feDropShadow dx="0" dy="${shadow / 2}" stdDeviation="${shadow}" flood-color="#0F1115" flood-opacity="0.22"/></filter>
</defs>
<rect x="${offset}" y="${offset}" width="${plate}" height="${plate}" rx="${radius}" fill="url(#plate)"${shadow > 0 ? ' filter="url(#shadow)"' : ''}/>
${mark(canvas / 2, (canvas - markHeight) / 2, markHeight)}
</svg>
`
}

/** The welcome window wordmark: mark and product name, centered in upstream's 472×40 frame. */
function wordmark() {
  const fontSize = 28
  const gap = 12
  const markHeight = 34
  const markWidth = markHeight * logoWidth / logoHeight
  // A semibold system font sets roughly 0.6em per Latin character.
  const textWidth = brand.productName.length * fontSize * 0.6
  const left = (472 - (markWidth + gap + textWidth)) / 2
  return `<svg width="472" height="40" viewBox="0 0 472 40" fill="none" xmlns="http://www.w3.org/2000/svg">
<style>
  :root { --brand-label: #0f1115; }
  @media (prefers-color-scheme: dark) { :root { --brand-label: #f9fafb; } }
  text { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "PingFang SC", "Microsoft YaHei", sans-serif; font-weight: 600; }
</style>
${mark(left + markWidth / 2, 3, markHeight)}
<text x="${(left + markWidth + gap).toFixed(2)}" y="30" font-size="${fontSize}" fill="var(--brand-label)">${escapeXml(brand.productName)}</text>
</svg>
`
}

/** Data module read by patches/0006; the upstream file holds the official copy. */
function brandModule(description) {
  return `/** ${description} Generated by scripts/brand.mjs from overlay/apps/desktop/branding/brand.json. */
export const brand = ${JSON.stringify({ productName: brand.productName, accountProvider: brand.accountProvider, accountName: brand.accountName, welcomeDescription: brand.welcomeDescription }, null, 2)} as const
`
}

function write(relative, content) {
  const path = join(OVERLAY, relative)
  mkdirSync(dirname(path), { recursive: true })
  writeFileSync(path, content)
  console.log(`agent-work: wrote overlay/${relative}`)
}

async function png(relative, svg, size) {
  const path = join(OVERLAY, relative)
  mkdirSync(dirname(path), { recursive: true })
  await sharp(Buffer.from(svg), { density: 300 }).resize(size, size).png().toFile(path)
  console.log(`agent-work: wrote overlay/${relative}`)
}

const macos = icon(1024, 824, 185, 14)
const windows = icon(1024, 1024, 200, 0)
const generic = icon(1104, 1024, 230, 16)
write('apps/desktop/resources/icon-macos.svg', macos)
write('apps/desktop/resources/icon-windows.svg', windows)
write('apps/desktop/resources/icon.svg', generic)
await png('apps/desktop/resources/icon-macos.png', macos, 1024)
await png('apps/desktop/resources/icon-windows.png', windows, 1024)
await png('apps/desktop/resources/icon.png', generic, 1104)
write('apps/desktop/renderer/assets/welcome-brand.svg', wordmark())

const favicon = `<svg width="${logoWidth}" height="${logoHeight}" viewBox="${viewBox.join(' ')}" fill="none" xmlns="http://www.w3.org/2000/svg">${logo.replace(/^[\s\S]*?<svg[^>]*>/u, '').replace(/<\/svg>\s*$/u, '')}</svg>\n`
write('apps/web/public/favicon.svg', favicon)
// The web console shows the same mark.
writeFileSync(join(ROOT, 'admin', 'static', 'logo.svg'), favicon)
console.log('agent-work: wrote admin/static/logo.svg')
write('apps/web/public/favicon-dark.svg', favicon)
const manifest = JSON.parse(readFileSync(join(ROOT, 'upstream', 'apps', 'web', 'public', 'manifest.webmanifest'), 'utf8'))
manifest.name = brand.productName
if ('short_name' in manifest) manifest.short_name = brand.productName
write('apps/web/public/manifest.webmanifest', `${JSON.stringify(manifest, null, 2)}\n`)

const markSvg = favicon.trim()
write('packages/client/ui-conversation/src/client/brand.ts', `/** Product identity in the empty conversation hero. Generated by scripts/brand.mjs from overlay/apps/desktop/branding/. */
export const brand: {
  readonly markSvg: string | null
  readonly heroHeadline: { readonly en: string; readonly zh: string } | null
  readonly heroPreview: boolean
} = ${JSON.stringify({ markSvg, heroHeadline: brand.heroHeadline ?? brand.welcomeDescription, heroPreview: brand.heroPreview ?? false }, null, 2)}
`)
write('packages/client/ui-brand-official/src/client/product.ts', `/** Product identity in the sidebar brand slots. Generated by scripts/brand.mjs from overlay/apps/desktop/branding/. */
export const brand: {
  readonly productName: string | null
  readonly markSvg: string | null
} = ${JSON.stringify({ productName: brand.productName, markSvg }, null, 2)}
`)
write('apps/desktop/src/brand.ts', brandModule('Product identity in Desktop shell copy.'))

// GL Work for iOS (mobile/ios): a full-bleed opaque icon (iOS rounds the corners and rejects alpha), and the mark for the sign-in screen.
const IOS_ASSETS = join(ROOT, 'mobile', 'ios', 'GLWork', 'Assets.xcassets')
mkdirSync(join(IOS_ASSETS, 'AppIcon.appiconset'), { recursive: true })
await sharp(Buffer.from(icon(1024, 1024, 0, 0)), { density: 300 }).resize(1024, 1024).flatten({ background: '#FFFFFF' }).removeAlpha().png()
  .toFile(join(IOS_ASSETS, 'AppIcon.appiconset', 'AppIcon-1024.png'))
console.log('agent-work: wrote mobile/ios/GLWork/Assets.xcassets/AppIcon.appiconset/AppIcon-1024.png')
mkdirSync(join(IOS_ASSETS, 'BrandMark.imageset'), { recursive: true })
writeFileSync(join(IOS_ASSETS, 'BrandMark.imageset', 'logo.svg'), favicon)
writeFileSync(join(IOS_ASSETS, 'BrandMark.imageset', 'Contents.json'), `${JSON.stringify({
  images: [{ filename: 'logo.svg', idiom: 'universal' }], info: { author: 'xcode', version: 1 }, properties: { 'preserves-vector-representation': true },
}, null, 2)}\n`)
console.log('agent-work: wrote mobile/ios/GLWork/Assets.xcassets/BrandMark.imageset')
write('packages/client/ui-settings-account/src/client/brand.ts', brandModule('Product identity in account and onboarding copy.'))

for (const file of ['.env.macos', '.env.macos.example', '.env.windows.example']) {
  let env
  try { env = readFileSync(join(OVERLAY, 'apps', 'desktop', file), 'utf8') } catch { continue }
  const name = /^DSH_DESKTOP_PRODUCT_NAME="?([^"\n]*)"?$/mu.exec(env)?.[1]
  if (name !== undefined && name !== brand.productName) {
    console.warn(`agent-work: ${file} sets DSH_DESKTOP_PRODUCT_NAME="${name}", brand.json says "${brand.productName}"`)
  }
}

// GL Work on Orca (orca/, GL-Game-Group/gl-orca): the macOS app icon its packaging config
// (orca/config/glwork-builder.config.cjs) uses, as PNG and, on macOS, as .icns.
const ORCA_BRAND = join(ROOT, 'orca', 'resources', 'glwork')
mkdirSync(ORCA_BRAND, { recursive: true })
await sharp(Buffer.from(macos), { density: 300 }).resize(1024, 1024).png().toFile(join(ORCA_BRAND, 'icon.png'))
console.log('agent-work: wrote orca/resources/glwork/icon.png')
if (process.platform === 'darwin') {
  const { execFileSync } = await import('node:child_process')
  const { mkdtempSync, rmSync } = await import('node:fs')
  const { tmpdir } = await import('node:os')
  const iconset = join(mkdtempSync(join(tmpdir(), 'glwork-icon-')), 'icon.iconset')
  mkdirSync(iconset)
  for (const size of [16, 32, 128, 256, 512]) {
    for (const scale of [1, 2]) {
      await sharp(Buffer.from(macos), { density: 300 }).resize(size * scale, size * scale).png()
        .toFile(join(iconset, `icon_${size}x${size}${scale === 2 ? '@2x' : ''}.png`))
    }
  }
  execFileSync('iconutil', ['-c', 'icns', iconset, '-o', join(ORCA_BRAND, 'icon.icns')])
  rmSync(dirname(iconset), { recursive: true, force: true })
  console.log('agent-work: wrote orca/resources/glwork/icon.icns')
}

// GL Work on Orca's phone app (orca/mobile/glwork.config.js): a full-bleed opaque icon like
// mobile/ios's, and the mark centred on the splash screen's transparent 400×255 canvas.
const ORCA_MOBILE_BRAND = join(ROOT, 'orca', 'mobile', 'assets', 'glwork')
mkdirSync(ORCA_MOBILE_BRAND, { recursive: true })
await sharp(Buffer.from(icon(1024, 1024, 0, 0)), { density: 300 }).resize(1024, 1024).flatten({ background: '#FFFFFF' }).removeAlpha().png()
  .toFile(join(ORCA_MOBILE_BRAND, 'icon.png'))
const splashMark = await sharp(Buffer.from(favicon), { density: 600 }).resize({ height: 200 }).png().toBuffer()
await sharp({ create: { width: 400, height: 255, channels: 4, background: { r: 0, g: 0, b: 0, alpha: 0 } } })
  .composite([{ input: splashMark, gravity: 'centre' }]).png().toFile(join(ORCA_MOBILE_BRAND, 'splash-icon.png'))
console.log('agent-work: wrote orca/mobile/assets/glwork/icon.png, splash-icon.png')
// …and the mark the phone app draws in place of Orca's (OrcaLogo → GlWorkLogo in GL Work builds).
writeFileSync(join(ROOT, 'orca', 'mobile', 'src', 'eva', 'glwork', 'glwork-logo-mark.ts'),
  `// Generated by agent-work's \`pnpm brand\` from overlay/apps/desktop/branding/logo.svg; do not edit.\nexport const GLWORK_LOGO_SVG = ${JSON.stringify(favicon.trim())}\n`)
console.log('agent-work: wrote orca/mobile/src/eva/glwork/glwork-logo-mark.ts')
