/** Product identity in account and onboarding copy. Generated by scripts/brand.mjs from overlay/apps/desktop/branding/brand.json. */
export const brand = {
  "productName": "GL Work",
  "accountProvider": "GL Work",
  "accountName": {
    "en": "company account",
    "zh": "公司账号"
  },
  "welcomeDescription": {
    "en": "Work smart, earn more.",
    "zh": "高效工作，努力赚钱。"
  }
} as const
