/**
 * The company service's PostgreSQL schema, in numbered steps recorded in
 * `schema_version`: version 1 is the SQLite schema as it stood at its own
 * version 8 (members and credentials, login state, usage, vendors and keys,
 * subscriptions, system config, plugins, tunnels, voice). Later changes add a
 * step; a step never changes once released:
 * - 2: `tunnels.client`, which GL Work registered a 手机远程 tunnel (null: the DSH desktop).
 * - 3: `voice_catalog.state`: a voice is `available` (on the official list only), `enabled`
 *   (members see it) or `disabled` (added, hidden for now). Voices shown so far become
 *   `enabled`, the others `available`. `enabled` stays, written in step with `state`, so an
 *   older service still reads which voices members see.
 *
 * - Millisecond timestamps, GitHub ids and token counts are `bigint`; 0/1 flags stay `integer`.
 * - Every text column uses the "C" collation: comparisons and `order by` go by
 *   bytes, as SQLite's did, whatever the database's default locale.
 * - `seq` columns keep the order rows were added in (SQLite's rowid): lists
 *   that sort by creation time or name break ties by it, as SQLite's did.
 */
import type { Sql } from './sql.ts'

const T = 'text collate "C"'

const V1 = `
create table members (
  name ${T} primary key,
  github_id bigint not null unique,
  github_login ${T} not null,
  role ${T} not null check (role in ('member', 'admin')),
  status ${T} not null check (status in ('active', 'disabled')),
  created_at bigint not null,
  display_name ${T},
  team ${T} check (team in ('dev', 'product', 'qa')),
  tunnels integer not null default 0,
  ssh integer not null default 0
);
create table credentials (
  id ${T} primary key,
  member ${T} not null references members(name) on delete cascade,
  kind ${T} not null check (kind in ('device', 'browser', 'key', 'phone')),
  token_hash ${T} not null unique,
  label ${T} not null,
  created_at bigint not null,
  expires_at bigint not null,
  last_used_at bigint,
  revoked_at bigint,
  last_ip ${T},
  seq bigint generated by default as identity unique
);
create index credentials_member on credentials(member);
create table oauth_states (
  state_hash ${T} primary key,
  kind ${T} not null check (kind in ('web', 'desktop', 'phone')),
  return_to ${T},
  redirect_port integer,
  code_challenge ${T},
  client_state ${T},
  expires_at bigint not null
);
create table login_codes (
  code_hash ${T} primary key,
  member ${T} not null references members(name) on delete cascade,
  code_challenge ${T} not null,
  expires_at bigint not null,
  kind ${T} not null default 'desktop' check (kind in ('desktop', 'phone'))
);
create table audit (
  id bigint generated by default as identity primary key,
  at bigint not null,
  actor ${T},
  action ${T} not null,
  target ${T},
  detail ${T},
  ip ${T}
);
create table llm_usage (
  id bigint generated by default as identity primary key,
  at bigint not null,
  member ${T} not null,
  credential ${T} not null,
  model ${T},
  status integer not null,
  input_tokens bigint not null,
  output_tokens bigint not null,
  cache_read_tokens bigint not null,
  cache_write_tokens bigint not null,
  vendor ${T},
  api_key ${T}
);
create index llm_usage_member_at on llm_usage(member, at);
create table vendors (
  id ${T} primary key,
  name ${T} not null,
  type ${T} not null check (type in ('api', 'cli', 'voice')),
  auth ${T} not null check (auth in ('key', 'account')),
  protocol ${T} check (protocol in ('anthropic', 'openai', 'dashscope', 'volcengine')),
  base_url ${T},
  models_url ${T},
  compat ${T},
  models ${T} not null default '[]',
  catalog ${T} not null default '[]',
  catalog_at bigint,
  builtin integer not null default 0,
  created_at bigint not null,
  seq bigint generated by default as identity unique
);
create table api_keys (
  id ${T} primary key,
  vendor ${T} not null references vendors(id),
  label ${T} not null,
  secret ${T} not null,
  last4 ${T} not null,
  status ${T} not null check (status in ('active', 'disabled')),
  created_at bigint not null,
  mode ${T} not null default 'shared' check (mode in ('shared', 'dedicated')),
  seq bigint generated by default as identity unique
);
create table subscriptions (
  id ${T} primary key,
  vendor ${T} not null references vendors(id),
  plan ${T} not null,
  seats integer not null check (seats > 0),
  price ${T},
  cycle ${T} not null check (cycle in ('monthly', 'yearly')),
  renews_at bigint,
  owner ${T},
  note ${T},
  created_at bigint not null,
  seq bigint generated by default as identity unique
);
create table cli_accounts (
  id ${T} primary key,
  vendor ${T} not null references vendors(id),
  account ${T} not null,
  note ${T},
  created_at bigint not null,
  subscription ${T} references subscriptions(id) on delete set null,
  unique (vendor, account)
);
create table member_vendors (
  member ${T} not null references members(name) on delete cascade,
  vendor ${T} not null references vendors(id) on delete cascade,
  api_key ${T} references api_keys(id) on delete set null,
  cli_account ${T} unique references cli_accounts(id) on delete set null,
  created_at bigint not null,
  mode ${T} check (mode in ('shared', 'dedicated', 'account')),
  primary key (member, vendor)
);
create table public_config (
  key ${T} primary key,
  value ${T} not null,
  secret integer not null,
  note ${T},
  updated_at bigint not null,
  group_name ${T},
  reads bigint not null default 0,
  last_read_at bigint
);
create table plugins (
  name ${T} primary key,
  display_name ${T} not null,
  description ${T},
  version ${T} not null,
  url ${T} not null,
  integrity ${T} not null,
  size bigint not null,
  permissions ${T} not null default '[]',
  status ${T} not null check (status in ('published', 'hidden')),
  preinstalled integer not null default 0,
  created_at bigint not null,
  updated_at bigint not null,
  seq bigint generated by default as identity unique
);
create table device_plugins (
  credential ${T} not null references credentials(id) on delete cascade,
  plugin ${T} not null references plugins(name) on delete cascade,
  version ${T} not null,
  reported_at bigint not null,
  primary key (credential, plugin)
);
create table tunnel_domains (
  name ${T} primary key,
  is_default integer not null default 0,
  dns ${T} not null default 'unknown',
  cert ${T} not null default 'unknown',
  checked_at bigint,
  note ${T},
  created_at bigint not null,
  seq bigint generated by default as identity unique
);
create table tunnels (
  id ${T} primary key,
  member ${T} not null references members(name) on delete cascade,
  device ${T} not null,
  type ${T} not null check (type in ('http', 'ssh', 'remote')),
  name ${T} not null,
  domain ${T},
  local_port integer not null,
  protection ${T} not null default 'public' check (protection in ('public', 'password')),
  ssh_access ${T},
  secret_key ${T},
  public_port integer unique,
  closed_by ${T},
  online integer not null default 0,
  last_seen_at bigint,
  created_at bigint not null,
  updated_at bigint not null,
  unique (member, type, name),
  seq bigint generated by default as identity unique
);
create table app_settings (
  key ${T} primary key,
  value ${T} not null
);
create table voice_catalog (
  vendor ${T} not null references vendors(id) on delete cascade,
  id ${T} not null,
  name ${T} not null,
  description ${T},
  gender ${T} check (gender in ('female', 'male')),
  languages ${T},
  family ${T},
  models ${T} not null default '[]',
  sample_url ${T},
  enabled integer not null default 1,
  position integer not null,
  updated_at bigint not null,
  primary key (vendor, id)
);
create table voice_tokens (
  member ${T} not null,
  vendor ${T} not null,
  at bigint not null
);
create index voice_tokens_member on voice_tokens(member, at);
`

/** Built-in model vendors, in the order SQLite's v3 added them. */
export const SEED_VENDORS: [id: string, name: string, type: 'api' | 'cli', auth: 'key' | 'account', protocol: string | null, baseUrl: string | null, modelsUrl: string | null, compat: string | null, models: string][] = [
  ['codex', 'Codex', 'cli', 'account', null, null, null, null, '[]'],
  ['claude', 'Claude', 'cli', 'account', null, null, null, null, '[]'],
  ['qoder', 'Qoder', 'cli', 'account', null, null, null, null, '[]'],
  ['qwen', '千问', 'api', 'key', 'openai', 'https://dashscope.aliyuncs.com/compatible-mode/v1', null, '{"thinkingFormat":"qwen"}', '[]'],
  ['deepseek', 'DeepSeek', 'api', 'key', 'anthropic', 'https://api.deepseek.com/anthropic', 'https://api.deepseek.com/models', null,
    '[{"id":"deepseek-flash","name":"DeepSeek-V41-Flash"},{"id":"deepseek-v4-pro","name":"DeepSeek-V4-Pro"}]'],
]

/** Built-in voice vendors: Alibaba Model Studio (千问) and Volcengine (豆包语音). */
export const SEED_VOICE_VENDORS: [id: string, name: string, protocol: string, baseUrl: string][] = [
  ['qwen-voice', '千问语音', 'dashscope', 'https://dashscope.aliyuncs.com'],
  ['volc-voice', '火山语音', 'volcengine', 'https://openspeech.bytedance.com'],
]

interface Step {
  sql: string
  /** Rows the step seeds, in the same transaction. */
  seed?: (tx: Sql, now: number) => Promise<void>
}

const STEPS: Step[] = [
  {
    sql: V1,
    async seed(tx, now) {
      for (const row of SEED_VENDORS) {
        await tx.run('insert into vendors (id, name, type, auth, protocol, base_url, models_url, compat, models, builtin, created_at) values (?, ?, ?, ?, ?, ?, ?, ?, ?, 1, ?)', [...row, now])
      }
      for (const row of SEED_VOICE_VENDORS) {
        await tx.run(`insert into vendors (id, name, type, auth, protocol, base_url, builtin, created_at) values (?, ?, 'voice', 'key', ?, ?, 1, ?)`, [...row, now])
      }
    },
  },
  { sql: `alter table tunnels add column client ${T}` },
  {
    sql: `
alter table voice_catalog add column state ${T} not null default 'available' check (state in ('available', 'enabled', 'disabled'));
update voice_catalog set state = case when enabled = 1 then 'enabled' else 'available' end;
`,
  },
]

export const SCHEMA_VERSION = STEPS.length

/** An arbitrary constant: concurrent starts take turns migrating. */
const MIGRATION_LOCK = 72_000_001

/**
 * Bring the database up to {@link SCHEMA_VERSION}, each step in its own transaction.
 * @returns the version before migrating (0 for an empty database).
 */
export async function migrate(sql: Sql, now: () => number = Date.now): Promise<number> {
  await sql.exec('create table if not exists schema_version (version integer primary key, applied_at bigint not null)')
  let before: number | undefined
  for (;;) {
    const done = await sql.transaction(async (tx) => {
      await tx.query('select pg_advisory_xact_lock(?)', [MIGRATION_LOCK])
      const row = await tx.one<{ version: number | null }>('select max(version) as version from schema_version')
      const version = row?.version ?? 0
      before ??= version
      if (version > STEPS.length) throw new Error(`database: schema version ${String(version)} is newer than this service (${String(STEPS.length)}); update the service`)
      const step = STEPS[version]
      if (step === undefined) return true
      await tx.exec(step.sql)
      await step.seed?.(tx, now())
      await tx.run('insert into schema_version (version, applied_at) values (?, ?)', [version + 1, now()])
      return false
    })
    if (done) return before ?? 0
  }
}
